# Generated by Django 3.2.7 on 2021-09-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('calorie_content', models.IntegerField()),
                ('protein_content', models.IntegerField()),
                ('fat_content', models.IntegerField()),
                ('carbohydrate_content', models.IntegerField()),
                ('image', models.URLField(max_length=150)),
                ('category', models.ManyToManyField(related_name='foods', to='foods.Category')),
            ],
        ),
    ]
